# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

imports = [
	(modulesPath + "/installer/scan/not-detected.nix")
];

boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
boot.initrd.kernelModules = [ ];
boot.kernelModules = [ "kvm-intel" ];
boot.extraModulePackages = [ ];

fileSystems."/" = {
	device = "/dev/disk/by-uuid/3878a101-f097-41ee-bcbe-aecfd0378ad2";
	fsType = "ext4";
};

fileSystems."/boot" = {
	device = "/dev/disk/by-uuid/AAF1-FC2D";
	fsType = "vfat";
	options = [ "fmask=0077" "dmask=0077" ];
};

swapDevices = [
	{ device = "/dev/disk/by-uuid/438ca111-15bc-4266-a716-fc5ed32512de"; }
];

nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
